"""The gate that keeps `src/candi/README.md` from becoming a lie.

The page and everything under `src/candi/arch/` are generated by `tools/arch_diagram.py` out of a
real forward pass through `build_model()`. Generated is not the same as current: a generator nobody
re-runs produces a stale page that *looks* freshly made, which is worse than a stale comment because
a reader has no reason to doubt it. This is the thing that re-runs it.

TWO GATES, ON PURPOSE
---------------------
`test_committed_page_matches_the_model` is the real one — it regenerates every artifact and compares
byte for byte. It needs the `test` extra (torchview, torchinfo, graphviz) and the `dot` binary, so it
SKIPS on a machine that has only the training deps.

`test_headline_numbers_match_a_freshly_built_model` needs nothing but torch and therefore never
skips. It re-derives the numbers a reader actually acts on — the parameter total, the latent width,
the input and output shapes — and checks the committed page against them. A checkout where the byte
gate is skipped still cannot ship a README that misstates the model's size or its interface.

When either fails, the fix is one command:

    python tools/arch_diagram.py build
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
TOOLS = REPO / "tools"
README = REPO / "src" / "candi" / "README.md"
ARCH_JSON = REPO / "src" / "candi" / "arch" / "arch.json"

REBUILD = "run `python tools/arch_diagram.py build` and commit the result"


def _load_tool():
    """Import `tools/arch_diagram.py` — it is a script, not a package module."""
    if str(TOOLS) not in sys.path:
        sys.path.insert(0, str(TOOLS))
    return pytest.importorskip(
        "arch_diagram", reason="the architecture page needs the [test] extra (torchview, torchinfo)")


def test_the_page_and_its_artifacts_are_committed() -> None:
    """Cheapest possible failure first: the files exist at all."""
    for path in (README, ARCH_JSON,
                 ARCH_JSON.parent / "candi_graph.dot",
                 ARCH_JSON.parent / "candi_graph.svg",
                 ARCH_JSON.parent / "torchinfo.txt"):
        assert path.exists(), f"{path.relative_to(REPO)} is missing — {REBUILD}"


def test_headline_numbers_match_a_freshly_built_model() -> None:
    """No torchview, no graphviz, no skip. Builds the model and checks what a reader would quote."""
    pytest.importorskip("torch", reason="the model needs torch")
    src = REPO / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    from candi.model import build_model

    model = build_model()
    total = sum(p.numel() for p in model.parameters())
    spec = json.loads(ARCH_JSON.read_text(encoding="utf-8"))
    page = README.read_text(encoding="utf-8")

    assert spec["params"]["total"] == total, (
        f"arch.json records {spec['params']['total']:,} parameters; the model has {total:,} — {REBUILD}")
    assert f"{total:,} parameters" in page, (
        f"src/candi/README.md does not state the model's {total:,} parameters — {REBUILD}")

    enc, dec = model.encoder, model.decoder
    for key, want in (("num_tracks", enc.num_tracks), ("context_bins", enc.l1),
                      ("latent_bins", enc.l2), ("d_model", enc.d_model),
                      ("resolution_bp", enc.resolution),
                      ("dna_length_bp", enc.required_dna_len),
                      ("decoder_lane", dec.lane)):
        assert spec["derived"][key] == want, (
            f"arch.json says {key}={spec['derived'][key]}, the model says {want} — {REBUILD}")

    assert spec["io"]["inputs"]["x_data"] == ["B", enc.l1, enc.num_tracks], REBUILD
    assert spec["io"]["inputs"]["x_dna"] == ["B", 4, enc.required_dna_len], REBUILD
    assert sorted(spec["io"]["outputs"]) == sorted(("p", "n", "eta", "log2_mu", "mu")), (
        f"the page lists the output keys {sorted(spec['io']['outputs'])} — {REBUILD}")


def test_every_diagram_anchor_is_still_a_real_module() -> None:
    """A rename must fail here, not silently draw a diagram of a model that no longer exists."""
    pytest.importorskip("torch", reason="the model needs torch")
    src = REPO / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    from candi.model import build_model

    if str(TOOLS) not in sys.path:
        sys.path.insert(0, str(TOOLS))
    # Imported for ANCHORS alone, which costs nothing — the torchview import inside the tool is
    # lazy, so this works without the [test] extra.
    from arch_diagram import ANCHORS

    paths = {p for p, _ in build_model().named_modules()}
    missing = [a for a in ANCHORS if a not in paths]
    assert not missing, (
        f"tools/arch_diagram.py draws the modules {missing}, which no longer exist on a default "
        "CandiModel. Update ANCHORS to the paths that do exist, then rebuild the page.")


def test_committed_page_matches_the_model() -> None:
    """The real gate. Regenerate everything and compare byte for byte.

    `candi_graph.svg` is deliberately outside the comparison — graphviz's layout is stable within a
    version, not across them, so gating the rendered picture would make `brew upgrade graphviz` fail
    a test about a model nobody touched. The DOT it is rendered from IS compared, and the DOT is
    where the meaning lives.
    """
    tool = _load_tool()
    if shutil.which("dot") is None:
        pytest.skip("graphviz's `dot` binary is not on PATH")
    assert tool.cmd_check() == 0, (
        "src/candi/README.md or an artifact under src/candi/arch/ no longer matches the model "
        f"(the mismatch is printed above) — {REBUILD}")
