title: CANDII
slug: candii
root_id: root
engine_version: 3.4
counter_q: 4
counter_h: 16
counter_s: 0
counter_t: 119
task_categories: data-acquisition, hpc-setup, implementation, visualization, manuscript, admin
