#!/bin/bash
# t31 (a child of t30) — calibration (a): what a mid-training check COSTS, and whether it can tell
# two epochs apart.
#
#   sbatch slurm/t31_calib_timing.sh
#
# Calibration (b) (`tools/window_content.py`, run on the store) already priced coverage from the
# DATA: on chr21 the shipped 8 windows per target carry a relative standard error of 1.79, and
# 48.7% of windows hold no foreground bin at all. What it could not supply is the constant — it
# scored a surrogate, not a trained model — nor the epoch-to-epoch gain, which is what decides
# whether a check is worth running at all.
#
# ONE run answers both, because the hook scores the SAME model state at every coverage level in
# turn. Six runs at six coverages would spend six times the GPU and learn less, since the six runs
# would also differ from each other.
#
# THE REGIME MUST DECLARE `eval_pairs` (D31). Neither shipped regime does, which is why a
# store-backed run had nothing to score even after t28 taught the scorer to take a store dataset.
# `configs/regime.eic_val.json` is generated by `tools/split_regime_by_panel.py --split validation`:
# 26 pairs, `T_X` prompting and `V_X` as the truth. The TEST regime (`B_X`, 12 pairs) is a separate
# file on purpose — a single regime carrying both would put the test set inside the selection loop.
#
# --gres is the HARD-RULE MIG slice — never any other spec.
#SBATCH --account=def-maxwl
#SBATCH --job-name=candi_t31
#SBATCH --output=slurm-logs/t31_%x_%j.out
#SBATCH --error=slurm-logs/t31_%x_%j.err
#SBATCH --time=08:00:00
#SBATCH --gres=gpu:nvidia_h100_80gb_hbm3_1g.10gb:1
#SBATCH --mem=32G
#SBATCH --cpus-per-task=2

set -uo pipefail
KIT="${KIT:-$HOME/projects/def-maxwl/$USER/CANDII}"
VENV="${VENV:-$HOME/projects/def-maxwl/$USER/candi_venv}"
REGIME="${REGIME:-configs/regime.eic_val.json}"
OUT="${OUT:-/scratch/$USER/candi_kit/calib_a}"
EPOCHS="${EPOCHS:-10}"
STEPS="${STEPS:-200}"
# 2 / 8 / 32 / 128 cycles = 8 / 32 / 128 / 512 windows per target = 0.45% / 1.8% / 7.2% / 29% of
# chr21. The first is what the loader ships with today. The ANCHOR is -1, meaning whole chr21 per
# target, READ OFF THE DATASET rather than typed here: chr21 tiles to 2,432 windows on paper and
# 1,786 after the window plan's validity filter, so a literal here would already be wrong once. It
# runs at the FINAL epoch only: it is what every cheap level is trying to estimate, so
# without it "stable" and "accurate" cannot be told apart, but bias is a property of the coverage
# and does not need re-measuring every epoch.
LEVELS="${LEVELS:-2 8 32 128}"
ANCHOR="${ANCHOR:--1}"
SEED="${SEED:-0}"

export PYTHONNOUSERSITE=1 PYTHONUNBUFFERED=1; unset PYTHONPATH || true
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export MPLBACKEND=Agg WANDB_MODE=disabled
module load StdEnv/2023 python/3.10.13 >/dev/null 2>&1
source "$VENV/bin/activate" || { echo "[error] no venv at $VENV" >&2; exit 1; }
cd "$KIT"; mkdir -p "$OUT" slurm-logs
source "$KIT/slurm/_kit_pin.sh"
echo "[t31] regime=$REGIME epochs=$EPOCHS levels='$LEVELS' anchor=$ANCHOR seed=$SEED"
echo "[t31] host=$(hostname) commit=$(git rev-parse --short HEAD)"
nvidia-smi -L || true


python tools/calib_timing.py \
  --regime "$REGIME" --out "$OUT" \
  --epochs "$EPOCHS" --steps-per-epoch "$STEPS" \
  --levels $LEVELS --anchor-level "$ANCHOR" \
  --seed "$SEED" --heads count
rc=$?
echo "[t31] exit=$rc"
exit $rc
